# Generated by Django 4.0 on 2021-12-21 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOTTLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='BRAND',
            fields=[
                ('brand_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='HISTORY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ROOM',
            fields=[
                ('room_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SIZE',
            fields=[
                ('bottle_size', models.DecimalField(decimal_places=2, max_digits=4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='STOCK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('stock_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='water.bottle')),
            ],
        ),
        migrations.CreateModel(
            name='HISTORY_DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.history')),
                ('models', models.ManyToManyField(to='water.STOCK')),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='water.room'),
        ),
        migrations.AddField(
            model_name='bottle',
            name='bottle_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.size'),
        ),
        migrations.AddField(
            model_name='bottle',
            name='brand_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.brand'),
        ),
    ]
