# Generated by Django 4.0 on 2021-12-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HISTORY_DETAILS',
            new_name='HISTORYDETAIL',
        ),
        migrations.RenameField(
            model_name='bottle',
            old_name='price',
            new_name='buy_price',
        ),
        migrations.AddField(
            model_name='bottle',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
