# Generated by Django 4.0 on 2021-12-24 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_rename_history_details_historydetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottle',
            name='buy_price',
        ),
        migrations.RemoveField(
            model_name='bottle',
            name='sell_price',
        ),
        migrations.CreateModel(
            name='BOTTLE_DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.bottle')),
            ],
        ),
        migrations.AlterField(
            model_name='historydetail',
            name='models',
            field=models.ManyToManyField(to='water.BOTTLE_DETAILS'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='water.bottle_details'),
        ),
    ]
