# Generated by Django 4.0 on 2021-12-25 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0003_remove_bottle_buy_price_remove_bottle_sell_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historydetail',
            name='models',
        ),
        migrations.AddField(
            model_name='historydetail',
            name='bottle_detail',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='water.bottle_details'),
        ),
    ]
