# Generated by Django 4.0 on 2022-01-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0006_historydetail_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='historydetail',
            name='comlimentary',
            field=models.BooleanField(default=False),
        ),
    ]
