# Generated by Django 4.0 on 2022-01-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0010_alter_historydetail_complimentary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historydetail',
            old_name='complimentary',
            new_name='notcomplimentary',
        ),
    ]
