# Generated by Django 4.0 on 2022-01-05 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0011_rename_complimentary_historydetail_notcomplimentary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historydetail',
            name='notcomplimentary',
        ),
    ]
