# Generated by Django 4.0 on 2022-01-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0012_remove_historydetail_notcomplimentary'),
    ]

    operations = [
        migrations.AddField(
            model_name='historydetail',
            name='notcomplimentary',
            field=models.IntegerField(default=1),
        ),
    ]
