# Generated by Django 4.0 on 2022-01-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0013_historydetail_notcomplimentary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
